name: Test ScrollScan API Integration

on:
  push:
    branches: [ main, master, develop ]
    paths:
      - 'apis/scrollscan/**'
      - '.github/workflows/test-scrollscan-api.yml'
  pull_request:
    branches: [ main, master, develop ]
    paths:
      - 'apis/scrollscan/**'
      - '.github/workflows/test-scrollscan-api.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [20.15]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: 'apis/scrollscan/package-lock.json'
        
    - name: Install dependencies
      working-directory: ./apis/scrollscan
      run: npm ci --legacy-peer-deps
      
    - name: Run linting
      working-directory: ./apis/scrollscan
      run: |
        # Check if TypeScript is properly configured
        npx tsc --noEmit --skipLibCheck
        
    - name: Validate secrets
      run: |
        echo "🔍 Debugging secrets..."
        echo "SCROLLSCAN_API_KEY length: ${#SCROLLSCAN_API_KEY}"
        
        if [ -z "${{ secrets.SCROLLSCAN_API_KEY }}" ]; then
          echo "❌ SCROLLSCAN_API_KEY secret is not set or empty"
          echo "Available secrets:"
          echo "  - SCROLLSCAN_API_KEY: '${{ secrets.SCROLLSCAN_API_KEY }}'"
          echo ""
          echo "💡 To fix this:"
          echo "1. Go to your repository Settings"
          echo "2. Click 'Secrets and variables' → 'Actions'"
          echo "3. Add a new secret named exactly 'SCROLLSCAN_API_KEY'"
          echo "4. Set the value to your ScrollScan API key"
          exit 1
        fi
        echo "✅ All required secrets are available"
        
    - name: Run tests
      working-directory: ./apis/scrollscan
      run: npm test
      env:
        SCROLLSCAN_API_KEY: ${{ secrets.SCROLLSCAN_API_KEY }}
      continue-on-error: false
        
        
    - name: Comment PR with test results
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          const comment = `
          ## ✅ ScrollScan API Tests Completed
          
          Tests have been successfully executed for the ScrollScan API integration.
          
          ### Test Details
          - **Node.js Version**: ${{ matrix.node-version }}
          - **OS**: Ubuntu Latest
          - **Test Framework**: Jest
          - **API Integration**: ScrollScan Explorer API
          - **Network**: Scroll Sepolia Testnet
          
          ### What was tested:
          - ✅ Environment variables validation
          - ✅ API connectivity to ScrollScan
          - ✅ Current block number fetching
          - ✅ Block number validation (not zero)
          - ✅ API connectivity
          - ✅ Proper script exit handling
          `;
          
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: comment
          });
